### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 1-2: invalid continuation byte

### ISSUE THREAD

**Issue by artadp** [kevinheavey/anchorpy#109]
In the dynamic client after loading the program accounts, I want to decode the data:

```
http_client = Client("https://api.devnet.solana.com")
pubkey = PublicKey("...")

accounts = []

for x in http_client.get_program_accounts_json_parsed(pubkey).value:
	accounts.append(x.account)
```
But, the bytes cannot be decoded:

`UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 1-2: invalid continuation byte`

What should I do?
Thanks a lot.

**Comment by kevinheavey** [comment]
Can you give a reproducible example please?

**Comment by artadp** [comment]
This was the main code. I am just trying to load the accounts from the main program and nothing more. I don't know what do you want exactly

**Comment by kevinheavey** [comment]
I'm looking for a minimal reproducible example please https://stackoverflow.com/help/minimal-reproducible-example

**Comment by artadp** [comment]
Ok got it,
consider I have submitted multiple accounts using my wallet into the program. I have a program that makes the accounts containing three variables, var1, var2, and var3 (except the authority). 
The web interface makes multiple instances of that account:
ac1: var1, var2, var3
ac2: var1, var2, var3
now the network contains the ac1 and ac2, meaning that the program has two accounts.
Now I have the publickey
`pubkey = PublicKey("...")`
 of the program and I want to load and decode those variables(the three variables belong to ac1 and ac2) into my python program.

The client is connected to the program using publickey and tries to load the ac1 and ac2:
```
accounts = []

for x in http_client.get_program_accounts_json_parsed(pubkey).value:
	accounts.append(x.account)

```

**Comment by kevinheavey** [comment]
This runs fine on my machine with the latest solana-py and solders, though it prints an empty list (idk if that's what you expect):

```
from solana.rpc.api import Client
from solders.pubkey import Pubkey

http_client = Client("https://api.devnet.solana.com")
pubkey = Pubkey.from_string("E1g4fAGA38Q7yD2SuMZeemsm8T879jtqzrtch8ffMFHA")

accounts = []

for x in http_client.get_program_accounts_json_parsed(pubkey).value:
    accounts.append(x.account)

print(accounts)
```

If you update to the latest versions do you get the same behaviour?

Also this issue should be in the solana-py or solders repo, not here
