### ISSUE TITLE
Optional dependencies

### ISSUE THREAD

**Issue by ChristianCoenen** [kevinheavey/anchorpy#120]
Hey!

```python
typer = { version = "0.4.1", optional = true }
ipython = { version = "^8.0.1", optional = true }
genpy = {version = "^2021.1", optional = true }
black = {version = "^22.3.0", optional = true }
autoflake = { version = "^1.4", optional = true }
```

Is there a reason those are not listed as dev dependencies? With the current approach, they make dependency resolution in tools using `anchorpy` harder.

**Comment by kevinheavey** [comment]
These are used by `anchorpy client-gen` to format generated code. They're not dev dependencies
