### ISSUE TITLE
Client generation error

### ISSUE THREAD

**Issue by topeolatunji19** [kevinheavey/anchorpy#121]
Everytime I try using the `anchorpy client-gen idl.json client` command, I get this kind of error 

`apischema.validation.errors.ValidationError: ValidationError(messages=[], children={'instructions': ValidationError(messages=[], children={12: ValidationError(messages=[], children={'accounts': ValidationError(messages=[], children={2: ValidationError(messages=[], children={'isSigner': ValidationError(messages=['unexpected property'], children={}), 'accounts': ValidationError(messages=['missing property'], children={}), 'isMut': ValidationError(messages=['unexpected property'], children={}), 'isOptional': ValidationError(messages=['unexpected property', 'unexpected property'], children={})})})}), 16: ValidationError(messages=[], children={'accounts': ValidationError(messages=[], children={1: ValidationError(messages=[], children={'isSigner': ValidationError(messages=['unexpected property'], children={}), 'accounts': ValidationError(messages=['missing property'], children={}), 'isMut': ValidationError(messages=['unexpected property'], children={}), 'isOptional': ValidationError(messages=['unexpected property', 'unexpected property'], children={})})})}), 17: ValidationError(messages=[], children={'accounts': ValidationError(messages=[], children={1: ValidationError(messages=[], children={'isSigner': ValidationError(messages=['unexpected property'], children={}), 'accounts': ValidationError(messages=['missing property'], children={}), 'isMut': ValidationError(messages=['unexpected property'], children={}), 'isOptional': ValidationError(messages=['unexpected property', 'unexpected property'], children={})})})}), 18: ValidationError(messages=[], children={'accounts': ValidationError(messages=[], children={1: ValidationError(messages=[], children={'isSigner': ValidationError(messages=['unexpected property'], children={}), 'accounts': ValidationError(messages=['missing property'], children={}), 'isMut': ValidationError(messages=['unexpected property'], children={}), 'isOptional': ValidationError(messages=['unexpected property', 'unexpected property'], children={})})})})})})`

And its the same for all idls I have tried. Not sure what the cause of this issue is

**Comment by kevinheavey** [comment]
Looks like an old version of AnchorPy, can you try the latest version?

**Comment by topeolatunji19** [comment]
Done that, and now I get an error that says `solders.SerdeJSONError: unknown variant `hashMap`, expected one of `bool`, `u8`, `i8`, `u16`, `i16`, `u32`, `i32`, `f32`, `u64`, `i64`, `f64`, `u128`, `i128`, `bytes`, `string`, `publicKey`, `defined`, `option`, `vec`, `array` at line 4419 column 7`

**Comment by kevinheavey** [comment]
Same error as this then? https://github.com/kevinheavey/anchorpy/issues/114

**Comment by topeolatunji19** [comment]
Yes exactly
