### ISSUE TITLE
Issue with dependency

### ISSUE THREAD

**Issue by 8ball030** [kevinheavey/anchorpy#124]
https://github.com/kevinheavey/anchorpy/blob/5cb67a01a08afc52f5025b8e13e61ab97dc252fa/pyproject.toml#L13

@kevinheavey 
Not quite sure how this has happened, but you have bumped solana to 0.30.0

I am pretty it should still be at 0.29.0

https://github.com/michaelhly/solana-py/releases

**Comment by kevinheavey** [comment]
That was on purpose. Is something broken?

**Comment by 8ball030** [comment]
Ah nope, not when installing directly from main.

Any idea when the solana-py will be released?

pypi doesnt seem to like us referencing by git commit

I will close the issue, as this is patently user error my side sorry friend

**Comment by kevinheavey** [comment]
It's there no? https://pypi.org/project/solana/

**Comment by 8ball030** [comment]
Yeah it is! 
Sorry to have wasted your time here!

Its wierd, as it isnt on the releases page for solana;

`https://github.com/michaelhly/solana-py/releases`

Im going to blame the fact I have not had enough coffee yet
