### ISSUE TITLE
Installing zstandard (0.18.0): Failed

### ISSUE THREAD

**Issue by trycoast** [kevinheavey/anchorpy#134]
Using version ^0.18.0 for anchorpy

  c-ext\backend_c.c(13): fatal error C1083: Cannot open include file: 'Windows.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
  

  at ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\poetry\installation\chef.py:147 in _prepare
      143│
      144│                 error = ChefBuildError("\n\n".join(message_parts))
      145│
      146│             if error is not None:
    → 147│                 raise error from None
      148│
      149│             return path
      150│
      151│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with zstandard (0.18.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "zstandard (==0.18.0)"'.

I'm on Windows 11.

**Comment by trycoast** [comment]
Bumping zstandard to 0.22.0 works, but it's incompatable with anchorpy due to: 

Because no versions of anchorpy match >0.18.0,<0.19.0
 and anchorpy (0.18.0) depends on zstandard (>=0.18.0,<0.19.0), anchorpy (>=0.18.0,<0.19.0) requires zstandard (>=0.18.0,<0.19.0).

**Comment by kevinheavey** [comment]
Fixed by #132. anchorpy 0.19.0 removes the zstandard dependency
