### ISSUE TITLE
ModuleNotFoundError: No module named 'pytest_xprocess'

### ISSUE THREAD

**Issue by trycoast** [kevinheavey/anchorpy#135]
Hi,

When I try to install anchorpy 0.19.0 I get the following error:

ModuleNotFoundError: No module named 'pytest_asyncio'
[CMD]: poetry add pytest_asyncio
[CMD]: poetry run python -m main.py (script)
ModuleNotFoundError: No module named 'pytest_xprocess'
[CMD]: poetry add pytest_xprocess
[CMD]: poetry run python -m main.py (script)
ModuleNotFoundError: No module named 'pytest_xprocess'

It's possible that this is an issue on my end, but I don't know what would cause it in that case.

**Comment by kevinheavey** [comment]
I see you're installing pytest-xprocess and then can't import it. That seems unlikely to be affected by anchorpy as it doesn't do anything weird to your installed packages

**Comment by trycoast** [comment]
To clarify, I'm not using any of these packages, they were tagged as missing imports for anchorpy when trying to import a module from anchorpy.

```py
# main.py
from anchorpy import Program
```

That's the extent of the logic which triggres the ModuleNotFoundError for me.

**Comment by don1989** [comment]
Hopefully this helps someone else.

I had the same issue when updating to the latest version (0.19.1) with the "No module named 'pytest_xprocess' error", coming from anchorpy/pytest_plugin.py

Installing `pytest_xprocess` in my project didn't work.

I have tests of my own that I would run with `pytest`, and it would seem to pick up the plugin coming from anchor even though its an installed library. So I had to disable the pytest_anchorpy plugin with:

```
[pytest]
addopts = -s -p no:pytest_anchorpy
```

And now all good.
