### ISSUE TITLE
Unable to parse program IDL json

### ISSUE THREAD

**Issue by X0R0X** [kevinheavey/anchorpy#143]
I am following the tutorial of how to invoke a program via anchorpy, I've built and deployed the sample anchor hello-world application.

When i try to load the IDL, I've got the following error:
`   
idl = Idl.from_json(raw_idl)
solders.SerdeJSONError: data did not match any variant of untagged enum IdlAccountItem at line 26 column 8
`
Also, when I remove the account from the program and try to parse the IDL again, it expects all fields from the `metadata` dictionary to be top level.

Versions of  all components are the most recent (at the time of writing  this):
solana: 1.8.13
anchor: 0.30.0
anchorpy: 0.21

**Comment by X0R0X** [comment]
Ok, wrong anchor version, sorry.

**Comment by sunwk** [comment]
I encountered the same problem, how to solve it? thanks.
Versions of all components:
solana==0.33.0
solders==0.21.0
anchorpy==0.20.1
