### ISSUE TITLE
Can't import the Idl class : module 'graphql' has no attribute 'GraphQLResolveInfo'

### ISSUE THREAD

**Issue by p0st1t** [kevinheavey/anchorpy#15]
Hello, i try to import the Idl class like in the tutorial : 

`from anchorpy import Idl, Program`

But just this simple import make an error : 

> File "/home/user/Documents/Projects/solana/test.py", line 1, in <module>
>     from anchorpy import Idl, Program
>   File "/home/user/.local/lib/python3.9/site-packages/anchorpy/__init__.py", line 3, in <module>
>     from anchorpy.coder.coder import Coder, InstructionCoder, EventCoder, AccountsCoder
>   File "/home/user/.local/lib/python3.9/site-packages/anchorpy/coder/coder.py", line 1, in <module>
>     from anchorpy.coder.accounts import AccountsCoder
>   File "/home/user/.local/lib/python3.9/site-packages/anchorpy/coder/accounts.py", line 5, in <module>
>     from anchorpy.coder.idl import typedef_layout
>   File "/home/user/.local/lib/python3.9/site-packages/anchorpy/coder/idl.py", line 27, in <module>
>     from anchorpy.idl import (
>   File "/home/user/.local/lib/python3.9/site-packages/anchorpy/idl.py", line 4, in <module>
>     from apischema import deserialize, alias
>   File "/home/user/.local/lib/python3.9/site-packages/apischema/__init__.py", line 51, in <module>
>     from . import graphql  # noqa: F401
>   File "/home/user/.local/lib/python3.9/site-packages/apischema/graphql/__init__.py", line 14, in <module>
>     from .schema import ID, Query, Mutation, Subscription, graphql_schema
>   File "/home/user/.local/lib/python3.9/site-packages/apischema/graphql/schema.py", line 41, in <module>
>     from apischema.graphql.resolvers import (
>   File "/home/user/.local/lib/python3.9/site-packages/apischema/graphql/resolvers.py", line 125, in <module>
>     __error: Exception, __obj: Any, __info: graphql.GraphQLResolveInfo, **kwargs
> AttributeError: module 'graphql' has no attribute 'GraphQLResolveInfo'

I tried to re-install anchorpy, and graphql, but same error again...

Can someone know what it happen and can help me please ?

**Comment by kevinheavey** [comment]
What versions of the following libraries do you have installed in your environment?

- anchorpy
- apischema
- graphql

I probably need to make some dependencies more strict. But I need your help to figure out what to change :)

**Comment by p0st1t** [comment]
Thank you so much for your quickly response, really

anchorpy==0.3.0
apischema==0.15.7
graphql-core==2.2.1
graphql-relay==2.0.0

**Comment by kevinheavey** [comment]
Hmm what happens if you uninstall the graphql libraries? They're optional dependencies in `apischema`, but we don't use that part of `apischema`

**Comment by p0st1t** [comment]
It works ! I deleted all graphql dependencies and now there is no error.

Really thank you so much for your really quick help.
