### ISSUE TITLE
Constructing IDL-aware transactions / instructions / events etc from RPC response data

### ISSUE THREAD

**Issue by eyevz** [kevinheavey/anchorpy#30]
Hi, cool project! I'm trying to figure out whether I can parse JSON from, eg, `getTransaction` RPC call into a transaction and list of IDL-aware instructions with named args and accounts in the context.

Not to build instructions to send over RPC, but to parse historical transactions / logs events.

**Comment by eyevz** [comment]
Okay, I can be a bit clearer now:

I have an IDL and `solana.transaction.TransactionInstruction`, and I want  turn that into a `anchorpy.context.Context` populated accounts, and whatever is the appropriate structure to hold named instruction arguments.

Maybe the context part doesn't fit naturally into the `Coder` pattern here. But at least for the instruction arguments I feel like I should be able to add a `decode` method to `InstructionCoder`. Is that reasonable?

**Comment by kevinheavey** [comment]
The underlying library for all this borsh stuff actually gives us a `.parse` method on `InstructionCoder` already. Does that do what you want?

**Comment by eyevz** [comment]
ezpz, thank you!

**Comment by eyevz** [comment]
I'm reconstructing the historical state of the protocol by replaying transactions against a model.

**Comment by dahifi** [comment]
> 

Can you tell me how you worked this out? Doing the same thing and trying to figure out how to decode the ix name and parameters from an encoded event data. I know that if I can map the decoded IDs to the ix argument layouts I can map them perfectly, but IDK how to do that with Coder yet.
