### ISSUE TITLE
EventParser fails

### ISSUE THREAD

**Issue by eyevz** [kevinheavey/anchorpy#37]
It seems like the event parser is getting confused by my logs. Here is a snippet demonstrating the problem: https://gist.github.com/eyevz/5ec6bab673f4b2d5886bac32da6f3ce4

**Comment by kevinheavey** [comment]
Taking a look now @eyevz. Would you mind checking if it works fine with the parser in anchor-ts?

**Comment by eyevz** [comment]
Have not checked anchor-ts yet, need to finish something first. Just a note confirming that the event coder is fine, the problem is in event parser.
