### ISSUE TITLE
Update example to use async context manager

### ISSUE THREAD

**Issue by quazzuk** [kevinheavey/anchorpy#43]
is there a reason you're not doing:

```   
# Generate the program client from IDL.
async with Program(idl, program_id) as program:

    # Execute the RPC.
    await program.rpc["initialize"]()
```

instead of 

```
# Generate the program client from IDL.
program = Program(idl, program_id)

# Execute the RPC.
await program.rpc["initialize"]()

# Close the underlying http client, otherwise we get warnings.
await program.close()
```

Also, perhaps workspaces can be given an async context manager too?

?

**Comment by kevinheavey** [comment]
Yeah this makes sense.

> Also, perhaps workspaces can be given an async context manager too?

Probably not worth it as workspaces are just dictionaries currently and they're only for tests
