### ISSUE TITLE
Provided incorrect number of args to instruction

### ISSUE THREAD

**Issue by ciroartz** [kevinheavey/anchorpy#45]
Hello, I have a program in normal Anchor JS which works completely fine but when I try to rewrite it in python I get the following error: ("Provided incorrect number of args to instruction=exchange2. Expected ['expected_taker_amount', 'expected_mint']", "Received (100000000, *mintAddress here*, {'accounts': etc..)

I'm sending the request this way: sendTransaction = await meProgram.rpc['exchange2'](itemPriceU64, PublicKey(mintAddress), transactionObject) which is pretty much the same as I do with JS, although with the python client I get the issue I mentioned above. How would I go about fixing this? Thanks in advance.

Python Version = 3.9.7 64-bit
AnchorPy Version = 0.6.0

**Comment by kevinheavey** [comment]
You'll want to do 
```python
ctx = Context(accounts={"whatever_goes_here": whatever_goes_here})
await meProgram.rpc['exchange2'](itemPriceU64, PublicKey(mintAddress), ctx=ctx)
```

If you have any more problems feel free to ask in the anchor-py channel of the Anchor Discord https://discord.com/channels/889577356681945098

**Comment by ciroartz** [comment]
Thanks, and how would I go about supplying multiple arguments to the accounts parameter?

**Comment by kevinheavey** [comment]
It's just a dictionary so it can have multiple entries, if that's what you're asking. I'd suggest looking at the example in https://kevinheavey.github.io/anchorpy/testing/

**Comment by ciroartz** [comment]
Hey got that one thanks, also can you send me an invite to the discord server? that one is just a link to a channel. 

Now I am getting this error _AttributeError: 'dict' object has no attribute 'is_signer'_ - does this mean each key needs one extra parameter?

**Comment by kevinheavey** [comment]
Try this link: https://discord.gg/pauVaA5M

It's not clear without code or a traceback why you're getting that error

**Comment by ciroartz** [comment]
Just joined, I'm Ciro#0001 - let me know as soon as you can help me out there!
