### ISSUE TITLE
anchorpy cannot be installed in Mac yet?

### ISSUE THREAD

**Issue by Jyou965** [kevinheavey/anchorpy#46]
It can be installed in PCs, but cannot be installed in Mac.

**Comment by kevinheavey** [comment]
What happens when you try and install it?

**Comment by Jyou965** [comment]
![Screen Shot 2021-12-30 at 8 35 03 AM](https://user-images.githubusercontent.com/80657579/147765048-ad6ebdbd-9865-419d-ba80-82b366ccf511.png)

This is the error message.  Did I use the right command?

**Comment by Jyou965** [comment]
The requirement is:
anchorpy==0.4.3

**Comment by kevinheavey** [comment]
What Python version are you using? AnchorPy currently supports Python >= 3.9

**Comment by Jyou965** [comment]
oh, I'm using 3.8.  Is that the problem?

**Comment by kevinheavey** [comment]
Yes. I wish pip gave a better error message for this

**Comment by Jyou965** [comment]
Will do.  Thanks!

**Comment by Jyou965** [comment]
After updating to python 3.9.1, the installation still didn't work:

![Screen Shot 2021-12-30 at 9 31 25 AM](https://user-images.githubusercontent.com/80657579/147769476-7dcb8d92-6eea-455c-b547-8c1e3c8cae91.png)

**Comment by kevinheavey** [comment]
Would you mind doing `pip install anchorpy -v` to see more output?

**Comment by Jyou965** [comment]
Sure!  Looks like it's still using python 3.8...
![Screen Shot 2021-12-30 at 11 23 37 AM](https://user-images.githubusercontent.com/80657579/147777737-7e132399-fbfe-482d-8cb4-0b4215bd999f.png)
![Screen Shot 2021-12-30 at 11 23 55 AM](https://user-images.githubusercontent.com/80657579/147777743-9c693dbb-fb76-4edb-90c1-ea8cfb61a04a.png)

**Comment by kevinheavey** [comment]
That makes me feel better! Let me know if you get your Python environment fixed (good luck)

**Comment by kevinheavey** [comment]
Closing this but will re-open if it turns out there actually is a problem
