### ISSUE TITLE
Pytest dep

### ISSUE THREAD

**Issue by oldani** [kevinheavey/anchorpy#62]
Hi there,

Thanks for taking the time to create `anchorpy` and reading this. Any specific reason why pytest is included as a dependency and not in dev dependencies?

**Comment by kevinheavey** [comment]
It's an actual dependency because anchorpy ships with a pytest plugin

**Comment by block-chaynes** [comment]
I think ideally the pytest plugin would be a separate package

**Comment by kevinheavey** [comment]
Please open an issue if this is causing problems for you
